# Pharmacy service values override
serviceName: pharmacy
namespace: backend

image:
  repository: revanth654/healthcare-pharmacy
  tag: v2
  pullPolicy: Always

containerPort: 5001
replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  - name: PORT
    value: "5001"
  - name: MONGO_URI
    valueFrom:
      configMapKeyRef:
        name: backend-config
        key: MONGO_URI

service:
  type: ClusterIP
  port: 5001

probes:
  liveness:
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 5

initContainers:
  waitForMongo: true
  waitForRabbit: false

serviceAccountName: backend-sa
podAntiAffinity: true
